name: flutter_releaser
description: "A comprehensive desktop application updater and release tool that simplifies packaging, releasing, and updating Flutter desktop applications across Windows, Linux, and macOS platforms."
version: 0.0.2
resolution: workspace
homepage: https://github.com/Infumia/flutter_releaser/
repository: https://github.com/Infumia/flutter_releaser/

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.8
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  http: ^1.5.0
  package_info_plus: ^9.0.0
  pub_semver: ^2.2.0
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.10.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterReleaserPlugin
      macos:
        pluginClass: FlutterReleaserPlugin
      windows:
        pluginClass: FlutterReleaserPluginCApi
