name: flutter_releaser
description: "A comprehensive desktop application updater and release tool that simplifies packaging, releasing, and updating Flutter desktop applications across Windows, Linux, and macOS platforms."
version: 0.3.2
resolution: workspace
homepage: https://github.com/Infumia/flutter_releaser/
repository: https://github.com/Infumia/flutter_releaser/

environment:
  sdk: ^3.9.0

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  pub_semver: ^2.2.0
  archive: ^4.0.7
  path: ^1.9.1
  synchronized: ^3.4.0
  crypto: ^3.0.6

dev_dependencies:
  build_runner: ^2.10.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
