name: flutter_releaser_workspace
description: "A comprehensive desktop application updater and release tool that simplifies packaging, releasing, and updating Flutter desktop applications across Windows, Linux, and macOS platforms."
version: 0.0.1
homepage: https://github.com/Infumia/flutter_releaser/
repository: https://github.com/Infumia/flutter_releaser/
publish_to: none

workspace:
  - packages/flutter_releaser
  - packages/flutter_releaser_dio
  - packages/flutter_releaser_flutter
  - packages/flutter_releaser_hooks
  - applications/flutter_releaser_desktop
  - applications/flutter_releaser_cli

environment:
  sdk: ^3.9.0

dev_dependencies:
  flint: ^2.16.2
  melos: ^8.8.0

melos:
  scripts:
    flutter_clean:
      exec:
        command: flutter clean
        concurrency: 4
    watch:
      packageFilters:
        dependsOn: build_runner
      exec:
        command: dart run build_runner watch
        concurrency: 5
    build:
      packageFilters:
        dependsOn: build_runner
      exec:
        command: dart run build_runner build
        orderDependents: true
    get:
      exec:
        command: flutter pub get
        concurrency: 4
