name: flutter_releaser_workspace
description: "A comprehensive desktop application updater and release tool that simplifies packaging, releasing, and updating Flutter desktop applications across Windows, Linux, and macOS platforms."
version: 0.0.1
homepage: https://github.com/Infumia/flutter_releaser/
repository: https://github.com/Infumia/flutter_releaser/
publish_to: none

workspace:
  - packages/flutter_releaser
  - packages/flutter_releaser_widgets
  - packages/flutter_releaser_hooks

environment:
  sdk: ^3.9.0

dev_dependencies:
  flint: ^2.14.0
  melos: ^7.3.0

melos:
  command:
    version:
      linkToCommits: true
      branch: master
      workspaceChangelog: true
  scripts:
    fix:
      run: dart fix --apply && dart format .
      exec:
        concurrency: 4
    format:
      run: dart format .
      exec:
        concurrency: 4
    upgrade:
      run: dart pub upgrade --major-versions
      exec:
        concurrency: 4
    get:
      run: flutter pub get
      exec:
        concurrency: 4
    flutter_clean:
      run: flutter clean
      exec:
        concurrency: 4
    cache_repair:
      run: flutter pub cache repair
