name: flutter_releaser
description: "A comprehensive desktop application updater and release tool that simplifies packaging, releasing, and updating Flutter desktop applications across Windows, Linux, and macOS platforms."
version: 0.0.1
homepage: https://github.com/Infumia/flutter_releaser/
repository: https://github.com/Infumia/flutter_releaser/
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flint: ^2.14.0
  melos: ^7.3.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterReleaserPlugin
      macos:
        pluginClass: FlutterReleaserPlugin
      windows:
        pluginClass: FlutterReleaserPluginCApi

melos:
  scripts:
    fix:
      run: dart fix --apply && dart format .
      exec:
        concurrency: 4
    format:
      run: dart format .
      exec:
        concurrency: 4
    upgrade:
      run: dart pub upgrade --major-versions
      exec:
        concurrency: 4
    get:
      run: flutter pub get
      exec:
        concurrency: 4
    flutter_clean:
      run: flutter clean
      exec:
        concurrency: 4
    cache_repair:
      run: flutter pub cache repair
