name: flutter_releaser_hooks
description: "A collection of helpful Flutter hooks that provide easy integration with flutter_releaser's UpdateController for managing application updates in a reactive way."
version: 0.1.1
resolution: workspace
homepage: https://github.com/Infumia/flutter_releaser/
repository: https://github.com/Infumia/flutter_releaser/

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.21.3
  flutter_releaser: ^0.3.1
  flutter_releaser_flutter: ^0.1.1
