name: flutter_releaser_hooks
description: "A collection of helpful Flutter hooks that provide easy integration with flutter_releaser's UpdateController for managing application updates in a reactive way."
version: 0.0.2
resolution: workspace
homepage: https://github.com/Infumia/flutter_releaser/
repository: https://github.com/Infumia/flutter_releaser/
publish_to: "none"

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_releaser: ^0.0.3
  flutter_hooks: ^0.21.3
