name: flutter_releaser_http
description: HTTP implementation for flutter_releaser package, providing HTTP-based release checking and downloading capabilities for Flutter applications.
version: 0.1.1
resolution: workspace
homepage: https://github.com/Infumia/flutter_releaser/
repository: https://github.com/Infumia/flutter_releaser/

environment:
  sdk: ^3.9.0

dependencies:
  flutter_releaser: ^0.3.1
  http: ^1.5.0
