name: flutter_releaser_http
description: HTTP implementation for flutter_releaser package, providing HTTP-based release checking and downloading capabilities for Flutter applications.
version: 0.1.0+3
resolution: workspace
homepage: https://github.com/Infumia/flutter_releaser/
repository: https://github.com/Infumia/flutter_releaser/

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_releaser: ^0.3.0
  http: ^1.5.0
